### ISSUE TITLE
Capture tint colours to use as a placeholder in the image grid

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/scrapbook#49]
Here's an example of what I'm imagining:

<img width="1044" alt="Screenshot 2024-07-11 at 08 17 47" src="https://github.com/alexwlchan/scrapbook/assets/301220/4da57b74-aa0b-4c24-b650-028672198975">

**Comment by alexwlchan** [comment]
Here's an example of what the underlying HTML looks like:

```
<div class="card" style="background: #edbe98">
  <a href="IMG_5521.JPG">

    <img src="IMG_5521.JPG" loading="lazy" style="aspect-ratio: 0.9278350515463918">
  </a>
</div>
```

```css
.card a {
    display: block;
}

.card img {
    height: 200px;
}

.card {
    margin-right: 10px;
    margin-bottom: 10px;
    display: inline-block;
}
```
